In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('twitter_training.csv',names = ['id','entity','sentiment','content'])

In [3]:
data = data.sample(15000,random_state=42).reset_index(drop=True)

In [4]:
data.head()

,id,entity,sentiment,content
0,6789,Fortnite,Irrelevant,He said told u I'm getting in that box of a br...
1,4115,CS-GO,Positive,Yo this looks LIT! CS: GO / Overwatch combo
2,5665,HomeDepot,Negative,@HomeDepot attention executive administrators....
3,9369,Overwatch,Irrelevant,Guy has notified me and says that my name has ...
4,2476,Borderlands,Positive,F Loving the new DLC!!!. RhandlerR RhandlerR R...


In [5]:
data.isnull().sum()

id             0
entity         0
sentiment      0
content      136
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(114)

#### Data Cleaning

In [7]:
data = data.dropna()

In [8]:
data.isnull().sum()

id           0
entity       0
sentiment    0
content      0
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(90)

In [10]:
data.shape

(14864, 4)

In [11]:
data = data.drop_duplicates()

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.shape

(14774, 4)

In [14]:
data.head()

,id,entity,sentiment,content
0,6789,Fortnite,Irrelevant,He said told u I'm getting in that box of a br...
1,4115,CS-GO,Positive,Yo this looks LIT! CS: GO / Overwatch combo
2,5665,HomeDepot,Negative,@HomeDepot attention executive administrators....
3,9369,Overwatch,Irrelevant,Guy has notified me and says that my name has ...
4,2476,Borderlands,Positive,F Loving the new DLC!!!. RhandlerR RhandlerR R...


In [15]:
data.drop(columns = ['id','entity'],inplace = True)

In [16]:
data.reset_index(drop=True,inplace=True)

In [17]:
data

,sentiment,content
0,Irrelevant,He said told u I'm getting in that box of a br...
1,Positive,Yo this looks LIT! CS: GO / Overwatch combo
2,Negative,@HomeDepot attention executive administrators....
3,Irrelevant,Guy has notified me and says that my name has ...
4,Positive,F Loving the new DLC!!!. RhandlerR RhandlerR R...
...,...,...
14769,Positive,never get tired of getting the good weather aw...
14770,Positive,Sniper look smooth af on your cold war thank you.
14771,Neutral,Don't use me... @CSGO .. t medal.tv/clips/160...
14772,Irrelevant,for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...


In [18]:
data = data.rename(columns ={'sentiment':'Sentiment','content':'Tweet'})

In [19]:
data = data[(data['Sentiment']=='Positive') | (data['Sentiment']=='Negative') |(data['Sentiment']=='Neutral')]

In [20]:
data['Sentiment'].value_counts()

Sentiment
Negative    4471
Positive    4178
Neutral     3560
Name: count, dtype: int64

In [21]:
data.reset_index(drop=True,inplace=True)

#### Word Cloud for EDA of teaxt data to see which words are repeating more, etc.

## Feature Encoding

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
label = LabelEncoder()

In [24]:
data['Sentiment'] = label.fit_transform(data['Sentiment'])

In [104]:
for index, label1 in enumerate(label.classes_):
    print(index,label1)

0 Negative
1 Neutral
2 Positive


In [25]:
data

,Sentiment,Tweet
0,2,Yo this looks LIT! CS: GO / Overwatch combo
1,0,@HomeDepot attention executive administrators....
2,2,F Loving the new DLC!!!. RhandlerR RhandlerR R...
3,0,@ Rainbow6Game out on Xbox
4,2,you miss those Battlefield 1 days
...,...,...
12204,2,This is my nice way of ending GN with Kaid als...
12205,2,never get tired of getting the good weather aw...
12206,2,Sniper look smooth af on your cold war thank you.
12207,1,Don't use me... @CSGO .. t medal.tv/clips/160...


In [26]:
from tensorflow.keras.preprocessing.text import Tokenizer

Tokenizer need to handle out or vocab words

In [27]:
tokenizer = Tokenizer(oov_token=None)

In [28]:
tokenizer.fit_on_texts(data['Tweet'])

In [29]:
tokenizer.word_index ## All words in vocab

{'the': 1,
 'i': 2,
 'to': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'for': 8,
 'in': 9,
 'it': 10,
 'this': 11,
 'my': 12,
 'you': 13,
 'on': 14,
 'that': 15,
 'com': 16,
 'game': 17,
 'with': 18,
 'so': 19,
 'have': 20,
 'be': 21,
 'just': 22,
 'me': 23,
 'but': 24,
 'not': 25,
 'are': 26,
 'all': 27,
 'was': 28,
 'at': 29,
 'pic': 30,
 'like': 31,
 'twitter': 32,
 '2': 33,
 'out': 34,
 'your': 35,
 'from': 36,
 'get': 37,
 'now': 38,
 'we': 39,
 't': 40,
 'johnson': 41,
 'good': 42,
 'play': 43,
 'they': 44,
 'as': 45,
 'do': 46,
 'one': 47,
 'can': 48,
 'about': 49,
 'if': 50,
 'new': 51,
 'no': 52,
 'has': 53,
 'time': 54,
 'when': 55,
 'really': 56,
 'an': 57,
 'will': 58,
 'up': 59,
 'love': 60,
 "i'm": 61,
 'more': 62,
 'what': 63,
 'by': 64,
 'some': 65,
 '3': 66,
 'unk': 67,
 'why': 68,
 'how': 69,
 'shit': 70,
 'been': 71,
 'still': 72,
 'co': 73,
 'or': 74,
 "it's": 75,
 '’': 76,
 'people': 77,
 'rhandlerr': 78,
 'https': 79,
 'amazon': 80,
 'facebook': 81,
 'playing': 82

In [30]:
tokenizer.word_counts ## how many time a vocab word wa repeared, dictionary

OrderedDict([('yo', 52),
             ('this', 2366),
             ('looks', 172),
             ('lit', 20),
             ('cs', 68),
             ('go', 337),
             ('overwatch', 183),
             ('combo', 7),
             ('homedepot', 66),
             ('attention', 10),
             ('executive', 4),
             ('administrators', 3),
             ('if', 581),
             ('ever', 232),
             ('your', 710),
             ('stores', 31),
             ('are', 986),
             ('getting', 238),
             ('big', 149),
             ('delivery', 26),
             ('orders', 21),
             ('sent', 19),
             ('for', 2587),
             ('pallets', 2),
             ('of', 3211),
             ('bricks', 2),
             ('to', 4841),
             ('downtown', 3),
             ('areas', 8),
             ('that', 1726),
             ('you', 1974),
             ('effectively', 3),
             ('being', 191),
             ('used', 83),
             ('mainly', 

In [31]:
tokenizer.document_count ## Number of rows

12209

In [32]:
len(tokenizer.word_index) ## Unique word in vocab

17936

In [33]:
type(tokenizer.word_index)

dict

In [34]:
## Savde rows data in sequences
sequences = tokenizer.texts_to_sequences(data['Tweet'])

In [35]:
sequences

[[588, 11, 208, 1290, 473, 100, 199, 2798],
 [487,
  2170,
  4048,
  4904,
  50,
  154,
  35,
  890,
  26,
  150,
  246,
  1025,
  1247,
  1342,
  8,
  6538,
  6,
  6539,
  3,
  4905,
  2552,
  15,
  13,
  26,
  4906,
  190,
  393,
  2015,
  9,
  1092,
  10227,
  1,
  3524,
  6,
  1894,
  3121],
 [739, 772, 1, 51, 1026, 78, 78, 78, 30, 32, 16, 4907],
 [155, 34, 14, 97],
 [13, 360, 332, 220, 85, 280],
 [135,
  1895,
  99,
  1776,
  9,
  1,
  1598,
  572,
  1535,
  960,
  141,
  1093,
  1093,
  871,
  10228,
  186,
  3525,
  10229,
  4908,
  1138,
  10230,
  3526,
  673],
 [270,
  674,
  3122,
  4909,
  3527,
  34,
  2553,
  4910,
  154,
  12,
  6540,
  236,
  92,
  1,
  2553,
  237,
  28,
  6541],
 [61, 675, 10231, 8, 1, 17],
 [86,
  10232,
  4049,
  10233,
  961,
  324,
  127,
  1062,
  1027,
  45,
  3123,
  2332,
  6542,
  10234,
  14,
  4911,
  1,
  16,
  1673,
  139,
  229,
  1,
  4912,
  86,
  962,
  2333,
  3,
  13,
  4050,
  383,
  35,
  1599,
  262,
  34,
  3,
  86,
  307,
  14,

### Padding - make size similar for all the tweets

In [36]:
from keras.utils import pad_sequences

In [37]:
sequences = pad_sequences(sequences,padding='pre')

In [38]:
sequences

array([[    0,     0,     0, ...,   100,   199,  2798],
       [    0,     0,     0, ...,     6,  1894,  3121],
       [    0,     0,     0, ...,    32,    16,  4907],
       ...,
       [    0,     0,     0, ...,   299,   142,    13],
       [    0,     0,     0, ...,    40,    73, 17936],
       [    0,     0,     0, ..., 10204,  1282,  6408]],
      shape=(12209, 166), dtype=int32)

## Model Buiding without Embedding Layer

In [39]:
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Input
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split

In [40]:
y = data['Sentiment'].values

In [41]:
x= sequences

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
x_train.shape

(9767, 166)

In [44]:
y_train.shape

(9767,)

In [46]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(166,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

In [47]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [49]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test),batch_size=64)

Epoch 1/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.3586 - loss: 1.1193 - val_accuracy: 0.3702 - val_loss: 1.0910
Epoch 2/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.3598 - loss: 1.0941 - val_accuracy: 0.3374 - val_loss: 1.0907
Epoch 3/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.3620 - loss: 1.0925 - val_accuracy: 0.3702 - val_loss: 1.0903
Epoch 4/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - accuracy: 0.3553 - loss: 1.0924 - val_accuracy: 0.3731 - val_loss: 1.0888
Epoch 5/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - accuracy: 0.3622 - loss: 1.0916 - val_accuracy: 0.3718 - val_loss: 1.0888
Epoch 6/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.3628 - loss: 1.0914 - val_accuracy: 0.3747 - val_loss: 1.0891
Epoch 7/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - accuracy: 0.3539 - loss: 1.0920 - val_accuracy: 0.3722 - val_loss: 1.0882
Epoch 8/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - accuracy: 0.3564 - loss: 1.0914 - val_accu

## Model Buiding with Embedding Layer

In [50]:
vocab_size =  len(tokenizer.word_index)+1

In [51]:
vocab_size

17937

In [53]:
model2 = Sequential()
model2.add(Input(shape=(166,)))
model2.add(Embedding(input_dim=vocab_size,output_dim=64))
model2.add(Dense(3,activation='softmax'))

In [54]:
model2.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 166, 64)        │     1,147,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 166, 3)         │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,148,163 (4.38 MB)

 Trainable params: 1,148,163 (4.38 MB)

 Non-trainable params: 0 (0.00 B)

In [57]:
### Add everything

In [60]:
model_final = Sequential([
Embedding(input_dim=vocab_size,output_dim=128,input_shape=(166,),mask_zero=True),
SimpleRNN(32),
Dense(3,activation='softmax')
])

In [62]:
model_final.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 166, 128)       │     2,295,936 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         5,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,301,187 (8.78 MB)

 Trainable params: 2,301,187 (8.78 MB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model_final.compile(optimizer='adam',metrics = ['accuracy'],loss='sparse_categorical_crossentropy')

In [67]:
model_final.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),batch_size=64)

Epoch 1/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 52ms/step - accuracy: 0.9849 - loss: 0.0313 - val_accuracy: 0.7187 - val_loss: 1.1382
Epoch 2/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 52ms/step - accuracy: 0.9842 - loss: 0.0307 - val_accuracy: 0.7146 - val_loss: 1.1923
Epoch 3/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 7s 33ms/step - accuracy: 0.9844 - loss: 0.0301 - val_accuracy: 0.7174 - val_loss: 1.2109
Epoch 4/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9844 - loss: 0.0303 - val_accuracy: 0.7170 - val_loss: 1.2308
Epoch 5/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - accuracy: 0.9756 - loss: 0.0533 - val_accuracy: 0.6515 - val_loss: 1.4000
Epoch 6/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - accuracy: 0.9622 - loss: 0.0988 - val_accuracy: 0.7039 - val_loss: 1.1525
Epoch 7/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 46ms/step - accuracy: 0.9820 - loss: 0.0446 - val_accuracy: 0.7068 - val_loss: 1.1680
Epoch 8/50
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - accuracy: 0.9857 - loss: 0.0324 - val_accu

In [68]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [69]:
model_final.save('model.h5')

In [73]:
sum(model_final.predict(x_test)[0])

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step


np.float32(0.99999994)

In [90]:
import numpy as np
np.argmax(model_final.predict(x_test)[0:2],axis=1)

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step


array([0, 2])

In [88]:
model_final.predict(x_test)[:2]

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step


array([[9.9887735e-01, 9.8244101e-04, 1.4015567e-04],
       [5.4211807e-05, 2.6806658e-05, 9.9991894e-01]], dtype=float32)

In [99]:
model_final.predict(x_test[[0]])[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([9.9887735e-01, 9.8243961e-04, 1.4015580e-04], dtype=float32)

In [97]:
x_test

array([[   0,    0,    0, ...,   13,   19,  700],
       [   0,    0,    0, ...,    3,   92,   10],
       [   0,    0,    0, ...,  289,    8,   12],
       ...,
       [   0,    0,    0, ...,  122, 1954, 1562],
       [   0,    0,    0, ...,    3,   21, 6270],
       [   0,    0,    0, ..., 3437, 3407,   70]],
      shape=(2442, 166), dtype=int32)